dnd/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::group(['prefix'=>'admin','middleware'=>'auth'],function () {
	Route::get('/','HomeController@index');
	Route::get('getDeck','HomeController@getDeck');

	//personnel
	Route::resource('personnel','PersonnelController');
	Route::any('updatePersonnel','PersonnelController@updatePersonnel');
	Route::any('deact','PersonnelController@deact');
	Route::any('profile/{id}','PersonnelController@show_prof');
	Route::any('updateUser','UserController@updateUser');
		
	//Personnel schedule
	Route::resource('Psched','PscheduleController');
	Route::any('pSchedMany','PscheduleController@pSchedMany');

	//customer schedule + booking
	Route::resource('Csched','ScheduleController');
	Route::any('booking','ScheduleController@booking');
	Route::any('verifyTime','ScheduleController@verifyTime');
	Route::any('deny','ScheduleController@deny');
	
	//admin only links
	Route::middleware('Checkrole')->group(function () {
		

		//shift
		Route::resource('shift','ShiftController');
		Route::any('updateShift','ShiftController@updateShift');
		Route::any('deact_shift','ShiftController@deact');
			
		//services
		Route::resource('services','ServiceController');
		Route::any('sdeact','ServiceController@sdeact');
		Route::any('updateService','ServiceController@updateService');
		
		//rooms
		Route::resource('rooms','RoomController');
		Route::any('rdeact','RoomController@rdeact');
		Route::any('updateRoom','RoomController@updateRoom');


		//user
		Route::resource('users','UserController',['except'=>['show']]);
		Route::any('backup','UserController@backup');
		
		
		// Route::resource('monkeys', 'MonkeysController', [
		// 	'except' => ['edit', 'create']
		// ]);

		Route::any('deact_user','UserController@deact');
		Route::any('checkUsername', 'UserController@checkUsername');
		Route::any('resetPass', 'UserController@resetPass');
		
		Route::any('databackup','DatabaseBackupController@generateBackup');
	});

	//end admin only links
	
	Route::resource('users', 'UserController', [
			'only' => [ 'show']
	]);

	Route::any('changePass','UserController@changePass');

	Route::get('/rooms/clear/{id}','RoomController@clearRoom');
	Route::any('getTime','ShiftController@getTime');
	Route::any('saveSched','PscheduleController@saveSched');
	Route::any('savebSched','PscheduleController@savebSched');
	Route::any('editshed/{id}','PscheduleController@editshed');
	Route::any('editSched','PscheduleController@editSched');
	//printables
	Route::get('monthlysched/{month}','ReportController@monthlysched');
	Route::get('monthlyCsched/{month}','ReportController@monthlyCsched');

	//notifs
	Route::resource('/notifs', 'NotifController');
	Route::any('/toText', 'NotifController@toText');

	// functions
	Route::any('/getDeck','HomeController@getDeck');
	Route::any('/getRooms','HomeController@getRooms');
	Route::any('/getCschedule','HomeController@getCschedule');

	//test link
	Route::any('/testme','ScheduleController@testme');

	//Assignment
	Route::resource('/assignment','AssignmentController');

	//Deck

	
});


Route::get('/', function () {
      return view('welcome');
    // return redirect()->route('login');
});
// Route::get('/','HomeController@home');
Route::any('/saveCSchedH','HomeController@saveCschedH');
Route::any('/saveCSchedA','HomeController@saveCschedA');

dnd/app/Service.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    protected $fillable = [
        'name','duration','price','status',
    ];


    public function schedule(){
        return $this->hasMany('App\Cschedule');
    }
}

dnd/app/Http/Controllers/ServiceController.php
<?php

namespace App\Http\Controllers;

use App\Service;
use Illuminate\Http\Request;
use View;
class ServiceController extends Controller
{
    public function __construct()
    {
        date_default_timezone_set('Asia/Manila');
        View::share(["curpage"=>'Services']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $services = Service::all();
        return view('service.index',compact('services'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       $ps = Service::create([
            'name' => $request->name,
            'duration' => $request->duration,
            'price' => $request->price,
            'status' => 1,

        ]);

        if($ps)
            return "Success";
        else
            return "Error";
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function show(Service $service)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function edit(Service $service)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Service $service)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function destroy(Service $service)
    {
        //
    }

    public function sdeact(Request $request){
        $stat = 1;

        if($request->type == 1)
            $stat = 0;
        else
            $stat = 1;


        $update = Service::where('id',$request->id)->
        update([
            'status' => $stat
        ]);

        if($update)
            return 'Success';
        else
            return 'Error';
    }

    public function updateService(Request $request)
    {

        $update = Service::where('id',$request->id)->update([
            'name' => $request->name,
            'duration' => $request->duration,
            'price' => $request->price
        ]);

        if($update)
            return "Success";
        else
            return "Error";
    }
}

dnd/resources/views/service/add.blade.php
<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                      <div class="modal-dialog modal-notice">
                        <div class="modal-content">
                          <form id="addService" method="post" onsubmit="return addService();">
                          	<input hidden id="_token" name="_token" value="{{ Session::token() }}">
                          <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                              <i class="now-ui-icons ui-1_simple-remove"></i>
                            </button>
                            <h5 class="modal-title" id="myModalLabel">Add new Service</h5>
                          </div>
                          <div class="modal-body">
                            <div class="instruction">
					              <div class="input-group no-border">
					                <input name="name" id="name" type="text" value="" required class="form-control" placeholder="Service Name">
					                <div class="input-group-append">
					                  <div class="input-group-text">
					                    <i class="now-ui-icons travel_info" rel="tooltip" title="ie. Swidish, Foot Massage, etc."></i>
					                  </div>
					                </div>
					              </div>
					              <div class="input-group no-border">
					                <input name="duration" id="duration" type="number" value="" required class="form-control" placeholder="Duration in Minutes">
					                <div class="input-group-append">
					                  <div class="input-group-text">
					                    <i class="now-ui-icons travel_info" rel="tooltip" title="duration in minutes"></i>
					                  </div>
					                </div>
					              </div>
					              <div class="input-group no-border">
					                <input name="price" id="price" type="price" value="" required class="form-control" placeholder="Price">
					                <div class="input-group-append">
					                  <div class="input-group-text">
					                    <i class="now-ui-icons business_money-coins"></i>
					                  </div>
					                </div>
					              </div>
                            </div>
                            <p></p>
                          </div>
                          <div class="modal-footer justify-content-center">
                            <button class="btn btn-info btn-round" type="submit">Save <i class="now-ui-icons ui-1_send"></i></button>
                          </div>
                          </form>
                        </div>
                      </div>
             </div>

dnd/resources/views/service/edit.blade.php
               <div class="modal fade" id="editServie" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                      <div class="modal-dialog modal-notice">
                        <div class="modal-content">
                          <form method="post" id="editServie" onsubmit="return editService();">
                          <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                              <i class="now-ui-icons ui-1_simple-remove"></i>
                            </button>
                            <h5 class="modal-title" id="myModalLabel">Edit Service</h5>
                          </div>
                          <div class="modal-body">
                            <div class="instruction">
                            	<input name="eid" id="eid" type="text" hidden value="" required class="form-control" placeholder="Service Name">
					              <div class="input-group no-border">
					                <input name="ename" id="ename" type="text" value="" required class="form-control" placeholder="Service Name">
					                <div class="input-group-append">
					                  <div class="input-group-text">
					                    <i class="now-ui-icons travel_info" rel="tooltip" title="ie. Swidish, Foot Massage, etc."></i>
					                  </div>
					                </div>
					              </div>
					              <div class="input-group no-border">
					                <input name="eduration" id="eduration" type="number" value="" required class="form-control" placeholder="Duration in Minutes">
					                <div class="input-group-append">
					                  <div class="input-group-text">
					                    <i class="now-ui-icons travel_info" rel="tooltip" title="duration in minutes"></i>
					                  </div>
					                </div>
					              </div>
					              <div class="input-group no-border">
					                <input name="eprice" id="eprice" type="price" value="" required class="form-control" placeholder="Price">
					                <div class="input-group-append">
					                  <div class="input-group-text">
					                    <i class="now-ui-icons business_money-coins"></i>
					                  </div>
					                </div>
					              </div>
					          
                            </div>
                            <p></p>
                          </div>
                          <div class="modal-footer justify-content-center">
                            <button class="btn btn-info btn-round" type="submit">Update <i class="now-ui-icons ui-1_send"></i></button>
                          </div>
                          </form>
                        </div>
                      </div>
             </div>

dnd/resources/views/service/index.blade.php
@extends('layouts.app')
@section('content')
<div class="panel-header panel-header-sm"></div>
      <div class="content">
        <div class="row">
			<div class="col-md-12">
				<div class="card">
			              <div class="card-header">
			                <h4 class="card-title"><i class="now-ui-icons shopping_box"></i> Services</h4>
			              </div>
			              <div class="card-body">
			              					                <div class="table-responsive">
			                  <table id="datatable" class="table table-striped table-bordered" cellspacing="0" width="100%">
			                    <thead class=" text-primary">
			                      <tr align="center">
				                      <th>
				                        Name of Service
				                      </th>
				                      <th>
				                        Duration (minutes)
				                      </th>
				                      <th>
				                        Price
				                      </th>
				                      <th>
				                        Status
				                      </th>
				                      <th>
				                      	Actions
				                      </th>
			                      </tr>
			                    </thead>
			                    <tbody>
			                    	@if($services->count()>0)
				                    	@foreach($services as $row)
				                    		<tr class="text-center">
						                        <td class="text-left">
						                           {{$row->name}}
						                        </td>
						                        <td>
						                          {{$row->duration}}
						                        </td>
						                        <td>
						                          {{$row->price}}
						                        </td>
						                        <td>
						                        	@if($row->status ==1)
						                        		<span class="text-success">Active</span>
						                        	@else
						                        		<span class="text-danger">Inactive</span>
						                        	@endif
						                        </td>
						                        <td>
						                          <button  @if($row->status != 1) hidden @endif type="button" rel="tooltip" title="Edit" data-toggle="modal" data-target="#editServie" class="btn btn-tumblr btn-icon btn-sm " 
						                          		onclick="placeValue( {{$row->id}} ,'{{$row->name}}',{{$row->duration}},{{$row->price}})"
						                            >
						                            <i class="now-ui-icons ui-2_settings-90"></i>
						                          </button>
						                          @if($row->status == 1)
							                          <button type="button" rel="tooltip" title="Deactivate" onclick="deact({{$row->id}},1)" class="btn btn-danger btn-icon btn-sm ">
							                            <i class="now-ui-icons ui-1_simple-remove"></i>
							                          </button>
							                       @else
								                       <button type="button" rel="tooltip" title="Activate" onclick="deact({{$row->id}},2)" class="btn btn-success btn-icon btn-sm ">
								                            <i class="now-ui-icons ui-1_check"></i>
							                          </button>
							                       		
							                       @endif
						                        </td>
					                      	</tr>
				                    	@endforeach
				                    @else
				                    	<tr>
				                    		<td align="center" colspan="5">
				                    			<span class="text-primary">No data found</span>
				                    		</td>
				                    	</tr>
				                    @endif
			                    </tbody>
			                  </table>
			                   <button type="button" data-toggle="modal" data-target="#addModal" rel="tooltip" class="btn btn-info btn-round pull-right" data-original-title="" title="Add new Service">
				                            Add
				                            <i class="now-ui-icons ui-1_simple-add"></i>
				                </button>
			                </div>
			              </div>
			              @include('service/add')
             			  @include('service/edit')
			    </div>
			</div>
		</div>
	  </div>
</div>

<script>
	function placeValue(id,name,duration,price)
	{

		$('#eid').val(id);
		$('#ename').val(name);
		$('#eduration').val(duration);
		$('#eprice').val(price);

	}
	function deact(id,type)
	{
		if(type == 1)
			text = "deactivate";
		else
			text = "activate"
		swal({
	      title: 'Confirm',
	      text: "Are you sure you want to "+ text +" this service?",
	      type: 'warning',
	      showCancelButton: true,
	      confirmButtonColor: '#3085d6',
	      cancelButtonColor: '#d33',
	      confirmButtonText: text.toUpperCase(),
	    }).then((result) => {
			if(result){
				var form_data = {
					_token: $("input[name=_token]").val(),
					id:id,
					type:type
				};
				$.ajax({
			         url : "{{url('/')}}"+"/admin/sdeact",
			         data :  form_data,
			         type : "POST",
			        success : function(msg){
			            //success();
			            //console.log(msg);
			           
			            if(msg=="Error"){
			                error("The system encountered an error. Please contact the administrator.");
			            }

			            if(msg=="Success"){
			            	success("Service "+ text +"d successfully.");
			            	setTimeout(function(){window.location.reload();},1500);
			            }

			        }
			       }); 
			}
			
	    })
	}
	function addService()
	{
   		var form_data = $("#addService").serialize();
   		
       	$.ajax({
	         url : "{{route('services.store')}}",
	         data :  form_data,
	         type : "POST",
	         success : function(msg){
	            //success();
	            //console.log(msg);
	            var res = msg.split('|');
	            if(res[0]=="Error"){
	                error("The system encountered an error. Please contact the administrator.");
	            }
	            if(res[0]=="Success"){
	            	success('Service added successfully.')
	            	setTimeout(function(){window.location.reload();},1500);
	            }

	        }
       });
       return false;
	}

   function editService()
   {
	   var form_data={
	   		_token: $("input[name=_token]").val(),
	   		id: $('#eid').val(),
	   		name: $('#ename').val(),
	   		duration: $('#eduration').val(),
	        price: $('#eprice').val(),
	        ajax: 1
	   };
    
	   $.ajax({
	    url : "{{url('/')}}"+"/admin/updateService",
	     data :  form_data,
	     type : "POST",
	    success : function(msg){
	        //success();
	        console.log(msg);
	        if(msg=="Error"){
	            error("The system encountered an error. Please contact the administrator.");
	        }
	        if(msg=="Success"){
	        	success('Service updated.')
	        	setTimeout(function(){window.location.reload();},1500);
	        }

	    }
	   }); 
       return false;
   }
</script>
@endsection