dnd/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::group(['prefix'=>'admin','middleware'=>'auth'],function () {
	Route::get('/','HomeController@index');
	Route::get('getDeck','HomeController@getDeck');

	//personnel
	Route::resource('personnel','PersonnelController');
	Route::any('updatePersonnel','PersonnelController@updatePersonnel');
	Route::any('deact','PersonnelController@deact');
	Route::any('profile/{id}','PersonnelController@show_prof');
	Route::any('updateUser','UserController@updateUser');
		
	//Personnel schedule
	Route::resource('Psched','PscheduleController');
	Route::any('pSchedMany','PscheduleController@pSchedMany');

	//customer schedule + booking
	Route::resource('Csched','ScheduleController');
	Route::any('booking','ScheduleController@booking');
	Route::any('verifyTime','ScheduleController@verifyTime');
	Route::any('deny','ScheduleController@deny');
	
	//admin only links
	Route::middleware('Checkrole')->group(function () {
		

		//shift
		Route::resource('shift','ShiftController');
		Route::any('updateShift','ShiftController@updateShift');
		Route::any('deact_shift','ShiftController@deact');
			
		//services
		Route::resource('services','ServiceController');
		Route::any('sdeact','ServiceController@sdeact');
		Route::any('updateService','ServiceController@updateService');
		
		//rooms
		Route::resource('rooms','RoomController');
		Route::any('rdeact','RoomController@rdeact');
		Route::any('updateRoom','RoomController@updateRoom');


		//user
		Route::resource('users','UserController',['except'=>['show']]);
		Route::any('backup','UserController@backup');
		
		
		// Route::resource('monkeys', 'MonkeysController', [
		// 	'except' => ['edit', 'create']
		// ]);

		Route::any('deact_user','UserController@deact');
		Route::any('checkUsername', 'UserController@checkUsername');
		Route::any('resetPass', 'UserController@resetPass');
		
		Route::any('databackup','DatabaseBackupController@generateBackup');
	});

	//end admin only links
	
	Route::resource('users', 'UserController', [
			'only' => [ 'show']
	]);

	Route::any('changePass','UserController@changePass');

	Route::get('/rooms/clear/{id}','RoomController@clearRoom');
	Route::any('getTime','ShiftController@getTime');
	Route::any('saveSched','PscheduleController@saveSched');
	Route::any('savebSched','PscheduleController@savebSched');
	Route::any('editshed/{id}','PscheduleController@editshed');
	Route::any('editSched','PscheduleController@editSched');
	//printables
	Route::get('monthlysched/{month}','ReportController@monthlysched');
	Route::get('monthlyCsched/{month}','ReportController@monthlyCsched');

	//notifs
	Route::resource('/notifs', 'NotifController');
	Route::any('/toText', 'NotifController@toText');

	// functions
	Route::any('/getDeck','HomeController@getDeck');
	Route::any('/getRooms','HomeController@getRooms');
	Route::any('/getCschedule','HomeController@getCschedule');

	//test link
	Route::any('/testme','ScheduleController@testme');

	//Assignment
	Route::resource('/assignment','AssignmentController');

	//Deck

	
});


Route::get('/', function () {
      return view('welcome');
    // return redirect()->route('login');
});
// Route::get('/','HomeController@home');
Route::any('/saveCSchedH','HomeController@saveCschedH');
Route::any('/saveCSchedA','HomeController@saveCschedA');

dnd/app/Cschedule.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cschedule extends Model
{
    protected $fillable = [
        'lname','mname','fname','date','start','end','status','remarks','service_id','notified'
    ];

    public function service(){
        return $this->belongsTo('App\Service');
    }

}

dnd/resources/views/cschedule/add.blade.php
<div class="modal fade" id="addCSched" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
   <div class="modal-dialog modal-notice">
    <div class="modal-content">
		<div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
	          <i class="now-ui-icons ui-1_simple-remove"></i>
	        </button>
	        <h5 class="modal-title" id="myModalLabel">Walk - in Client</h5>
      	</div>
      	<div class="modal-body">
      	<form id="contactForm" onsubmit="return book();" name="contactForm">
	        <input hidden id="_token" name="_token" value="{{ Session::token() }}">
	        <div class="row">
	          <div class="col-md-6">
	            <div class="form-group">
	               <label class="text-white">First Name</label>
	              <input class="form-control" id="fname" name="fname" type="text" placeholder="Given Name*" required data-validation-required-message="Please enter your Given Name.">
	              <p class="help-block text-danger"></p>
	            </div>
	            <div class="form-group">
	               <label class="text-white">Middle Name</label>
	               <input class="form-control" id="mname" name="mname" type="text" placeholder="Middle Name (Optional)" >
	              <p class="help-block text-danger"></p>
	            </div>
	            <div class="form-group">
	               <label class="text-white">Last Name</label>
	              <input class="form-control" id="lname" name="lname" type="text" placeholder="Last Name*" required data-validation-required-message="Please enter your Last name.">
	              <p class="help-block text-danger"></p>
	            </div>
	            <div class="form-group">
	               <label class="text-white">Contact Number</label>
	              <input class="form-control" name="contact" id="contact" type="number" placeholder="Mobile Number *" required data-validation-required-message="Please enter your email address.">
	              <p class="help-block text-danger"></p>
	            </div>
	          </div>
	          <div class="col-md-6">
	            <div class="form-group">
	              <label class="text-white">Date</label>
	              <input class="form-control" name="date" id="date" type="date" placeholder="Date" value="{{date('Y-m-d')}}" required>
	              <p class="help-block text-danger"></p>
	            </div>
	             <div class="form-group">
	              <label class="text-white">Time</label>
	              <input class="form-control" name="start" id="start" type="time" placeholder="Time" required>
	              <p class="help-block text-danger"></p>
	            </div>
	           @php $services = Helper::getServices() @endphp
	            <div class="form-group">
	              <label class="text-white">Service</label>
	              <select class="form-control" name="service" id="service"  required data-validation-required-message="Please select a service.">
	                  <option disabled selected>Please Select a Service.</option>
	                  @foreach($services as $row)
	                      <option value="{{ $row->id }}"> {{$row->duration}} min. - {{$row->name}}</option>
	                  @endforeach
	              </select>
	              <p class="help-block text-danger"></p>
	            </div>
	          </div>
	          <div class="clearfix"></div>
	          <div class="col-lg-12 text-center">
	            <div id="success"></div>
	            <button id="sendMessageButton" class="btn btn-success btn-xl text-uppercase" type="submit">Book</button>
	          </div>
	        </div>
	      </form>
	   </div>
    </div>
  </div>
</div>

<script>
	function book(){
       var form_data = $("#contactForm").serialize();
       if($("#service").val() == null){
          error("Please select a service.");
        }else{
          $.ajax({
             url : "{{url('/')}}"+"/saveCSchedA",
             data :  form_data,
             type : "POST",
            success : function(msg){
                console.log(msg);
                  if(msg == "Success"){
  					success("Walkin client schedule added.");
    				setTimeout(function(){window.location.reload();},1500);
                  }else{
                    error('Something went wrong. Please contact your system administrator.');
                  }
                }
           });
          
        }
        return false;
     }
</script>

dnd/resources/views/cschedule/approval.blade.php
			<div class="col-md-12">
			            <div class="card">
			              <div class="card-header">
			                <h4 class="card-title"><i class="now-ui-icons business_badge"></i> New Booking</h4>
			              </div>
			              <div class="card-body">
			                <div class="table-responsive">
			                  <table id="datatable" class="table table-striped table-bordered" cellspacing="0" width="100%">
			                    <thead class=" text-primary">
			                      <tr align="center">
				                      <th>
				                        Name
				                      </th>
				                      <th>
				                        Date
				                      </th>
				                      <th>
				                        Time
				                      </th>
				                      <th>
				                        Service
				                      </th>
				                      <th>
				                        Status
				                      </th>
				                      <th>
				                      	Actions
				                      </th>
			                      </tr>
			                    </thead>
			                    <tbody id="tablereq">
			                    	
			                    	@if($approval->count()>0)
				                    	@foreach($approval as $row)
				                    		<tr class="text-center">
						                        <td class="text-left">
						                           {{$row->fname}} {{$row->mname[0]}}. {{$row->lname}}
						                        </td>
						                        <td>
						                          {{$row->date}}
						                        </td>
						                        <td>
						                          {{$row->start}} - {{$row->end}}
						                        </td>
						                        <td class="text-right">
													{{$row->service->duration}} mins. - {{$row->service->name}}
						                        </td>
						                        <td class="text-right">
						                        	For Approval
														<!-- 0-for approval
												        	1- active
												        	2- on-going
												        	3 - finished
												        	4 - cancelled -->
						                        </td>
						                        <td>
						                          
						                          <a @if($row->status != 1) hidden @endif type="button" rel="tooltip" title="Profile" class="btn btn-info btn-icon btn-sm" href="{{url('/admin/personnel',[$row->id])}}">
						                            <i class="now-ui-icons users_single-02"></i>
						                          </a>
						                          <button  @if($row->status != 1) hidden @endif type="button" rel="tooltip" title="Edit" data-toggle="modal" data-target="#editModal" class="btn btn-tumblr btn-icon btn-sm " 
						                          		onclick="placeValue( {{$row->id}} ,'{{$row->fname}}','{{$row->mname}}','{{$row->lname}}',{{$row->age}},'{{$row->gender}}', {{$row->salary}} ) "
						                            >
						                            <i class="now-ui-icons ui-2_settings-90"></i>
						                          </button>
								                       <button type="button" rel="tooltip" title="Approve" data-toggle="modal" data-target="#timeverify" rel="tooltip" onclick="verifyMe({{$row->id}},{{$row->service->duration}},'{{ $row->start }}','{{ $row->end }}','{{ $row->service->name}}' )" class="btn btn-success btn-icon btn-sm">
								                            <i class="now-ui-icons ui-1_check"></i>
							                          </button>
							                          <button type="button" rel="tooltip" title="Deny" onclick="deny({{$row->id}})" class="btn btn-danger btn-icon btn-sm ">
							                            <i class="now-ui-icons ui-1_simple-remove"></i>
							                          </button>
						                        </td>
					                      	</tr>
				                    	@endforeach
				                    @else
				                    	<tr>
				                    		<td align="center" colspan="6">
				                    			<span class="text-primary">No data found</span>
				                    		</td>
				                    	</tr>
				                    @endif
			                    </tbody>
			                  </table>
			                </div>
			              </div>
			            </div>
			  </div>
             @include('cschedule/timeverify')
	 <script type="text/javascript">
	 			function verifyMe(id,duration,start,end,service){
	 					$("#vid").val(id);
	 					$("#vduration").val(duration);
	 					$("#vstart").val(start);
	 					$("#vend").val(end);
	 					$("#vdisplay").val(end);
	 					$("#vservice").val(duration+"mins -"+service);
	 			}

	 			function deny(id)
	 			{
	 				swal({
			          title: 'Confirm',
			          text: "Are you sure you want to deny this booking?",
			          type: 'warning',
			          showCancelButton: true,
			          confirmButtonColor: '#3085d6',
			          cancelButtonColor: '#d33',
			          confirmButtonText: "Deny",
			        }).then((result) => {
						if(result){
							var form_data = {
								_token: $("input[name=_token]").val(),
								id:id
							};
							$.ajax({
						         url : "{{url('/')}}"+"/admin/deny",
						         data :  form_data,
						         type : "POST",
						        success : function(msg){
						            //success();
						            //console.log(msg);
						           
						           
						            if(msg=="Success"){
						            	success("Booking denied successfully.");
						            	setTimeout(function(){window.location.reload();},1500);
						            }else{
						            	text = msg.split("|")
						           	     error("The system encountered an error. Please contact the administrator." + text[0]);
						           
						            }

						        }
						       }); 
						}
						
			        })
	 			}

	 			function placeValue(id,fname,mname,lname,age,gender,salary)
	 			{

	 				$('#eid').val(id);
	 				$('#efname').val(fname);
	 				$('#emname').val(mname);
	 				$('#elname').val(lname);
	 				$('#eage').val(age);
	 				$('#egender').val(gender);
	 				$('#esalary').val(salary);

	 			}
    //document.getElementById("beg_date").onchange = function() {myFunction()};
			    function add_Personnel(){
			       var form_data={
			       		_token: $("input[name=_token]").val(),
			       		fname: $('#fname').val(),
			       		mname: $('#mname').val(),
			            lname: $('#lname').val(),
			            age: $('#age').val(),
			            gender: $('#gender').val(),
			            salary: $('#salary').val(),
			            ajax: 1
			       };
			       
			       if($('#gender').val()){
						       $.ajax({
						         url : "{{route('personnel.store')}}",
						         data :  form_data,
						         type : "POST",
						        success : function(msg){
						            //success();
						            //console.log(msg);
						            var res = msg.split('|');
						            if(res[0]=="Error"){
						                error("The system encountered an error. Please contact the administrator.");
						            }
						            if(res[0]=="Success"){
						            	success('Personnel added successfully.')
						            	setTimeout(function(){window.location.reload();},1500);
						            }

						        }
						       });
					}else{
						error('Please select a gender.');
					}

			           return false;
			       }

			       function edit_Personnel(){
			       var form_data={
			       		_token: $("input[name=_token]").val(),
			       		id: $('#eid').val(),
			       		fname: $('#efname').val(),
			       		mname: $('#emname').val(),
			            lname: $('#elname').val(),
			            age: $('#eage').val(),
			            gender: $('#egender').val(),
			            salary: $('#esalary').val(),
			            ajax: 1
			       };
			        
			       $.ajax({
			        url : "{{url('/')}}"+"/admin/updatePersonnel",
			         data :  form_data,
			         type : "POST",
			        success : function(msg){
			            //success();
			            console.log(msg);
			            if(msg=="Error"){
			                error("The system encountered an error. Please contact the administrator.");
			            }
			            if(msg=="Success"){
			            	success('Personnel updated.')
			            	setTimeout(function(){window.location.reload();},1500);
			            }

			        }
			       }); 
			           return false;
			       }

  </script>	

dnd/resources/views/cschedule/selectmonth.blade.php
   		<div class="modal fade" id="selectmonth" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                      <div class="modal-dialog modal-notice">
                        <div class="modal-content">
                          <div class="modal-header">
                            <button type="button" id="btnClose" class="close" data-dismiss="modal" aria-hidden="true">
                              <i class="now-ui-icons ui-1_simple-remove"></i>
                            </button>
                            <h5 class="modal-title" id="myModalLabel">Select Month</h5>
                          </div>
                          <div class="modal-body">
                            <div class="instruction">
                            	    <div class="input-group no-border col-md-6">
							                       <select id="month" name="month" class="selectpicker" required data-size="7" data-style="btn btn-round" title="month">
					                          
      					                          <option value="1" {{date('m') == 1 ? 'selected' : ''}}>January</option>
      					                          <option value="2" {{date('m') == 2 ? 'selected' : ''}}>February</option>
      					                          <option value="3" {{date('m') == 3 ? 'selected' : ''}}>March</option>
      					                          <option value="4" {{date('m') == 4 ? 'selected' : ''}}>April</option>
      					                          <option value="5" {{date('m') == 5 ? 'selected' : ''}}>May</option>
      					                          <option value="6" {{date('m') == 6 ? 'selected' : ''}}>June</option>
      					                          <option value="7" {{date('m') == 7 ? 'selected' : ''}}>July</option>
      					                          <option value="8" {{date('m') == 8 ? 'selected' : ''}}>August</option>
      					                          <option value="9" {{date('m') == 9 ? 'selected' : ''}}>September</option>
      					                          <option value="10" {{date('m') == 10 ? 'selected' : ''}}>October</option>
      					                          <option value="11" {{date('m') == 11 ? 'selected' : ''}}>November</option>
      					                          <option value="12" {{date('m') == 12 ? 'selected' : ''}} >December</option>

					                             </select>
							                     </div>
					                   </div> 
                              <p></p>
	                            <a class="btn btn-info btn-round pull-right"  style="float: right;"  onclick="selectmonth()">Select <i class="now-ui-icons ui-1_send"></i></a>
                              
                        </div>
                    </div>
              </div>
              <script>
              		function selectmonth(){
                    
                    $("#btnClose").click();
              			month = $('#month').val();
              			if(month >=1 )
              				window.open("{{url('admin/monthlyCsched/')}}/"+ month,'_blank');
              			else
              				error('Please select a month.');
              			
              		}
              </script>
        </div>

dnd/resources/views/cschedule/today.blade.php
			<div class="col-md-12">
			            <div class="card">
			              <div class="card-header">
			                <h4 class="card-title"><i class="now-ui-icons business_badge"></i> Today's Schedule</h4>
			              </div>
			              <div class="card-body">
			                <div class="table-responsive">
			                  <table id="datatable1" class="table table-striped table-bordered" cellspacing="0" width="100%">
			                    <thead class=" text-primary">
			                      <tr align="center">
				                      <th>
				                        Name
				                      </th>
				                      <th>
				                        Date
				                      </th>
				                      <th>
				                        Time
				                      </th>
				                      <th>
				                        Service
				                      </th>
				                      <th>
				                        Status
				                      </th>
				                      <th>
				                      	Actions
				                      </th>
			                      </tr>
			                    </thead>
			                    <tbody id="tablereq">
			                    	
			                    	@if($today->count()>0)
				                    	@foreach($today as $row)
				                    		<tr class="text-center">
						                        <td class="text-left">
						                           {{$row->fname}} @if($row->mname) {{$row->mname[0]}} @endif. {{$row->lname}}
						                        </td>
						                        <td>
						                          {{$row->date}}
						                        </td>
						                        <td>
						                          {{date("h:i: a", strtotime($row->start))}} - {{date('h:i: a',strtotime($row->end))}}
						                        </td>
						                        <td class="text-right">
													{{$row->service->duration}} mins. - {{$row->service->name}}
						                        </td>
						                        <td class="text-right">
						                        	For Approval
														<!-- 0-for approval
												        	1- active
												        	2- on-going
												        	3 - finished
												        	4 - cancelled -->
						                        </td>
						                        <td>
						            				
								                       <button @if($row->status == 1) hidden @endif type="button" rel="tooltip" title="Approve" data-toggle="modal" data-target="#timeverify" rel="tooltip" onclick="verifyMe({{$row->id}},{{$row->service->duration}},'{{ $row->start }}','{{ $row->end }}','{{ $row->service->name}}' )" class="btn btn-success btn-icon btn-sm">
								                            <i class="now-ui-icons ui-1_check"></i>
							                          </button>
							                          <button type="button" rel="tooltip" title="Deny" onclick="deny({{$row->id}})" class="btn btn-danger btn-icon btn-sm ">
							                            <i class="now-ui-icons ui-1_simple-remove"></i>
							                          </button>
						                        </td>
					                      	</tr>
				                    	@endforeach
				                    @else
				                    	<tr>
				                    		<td align="center" colspan="6">
				                    			<span class="text-primary">No data found</span>
				                    		</td>
				                    	</tr>
				                    @endif
			                    </tbody>
			                  </table>
			                   <button type="button" data-toggle="modal" data-target="#addCSched" rel="tooltip" class="btn btn-info btn-round pull-right" data-original-title="" title="Add Walk-in Client">
				                            Add
				                            <i class="now-ui-icons ui-1_simple-add"></i>
				                </button>
				                @include('cschedule.add')
				                
			                </div>
			              </div>
			            </div>
			  </div>
             
	 <script type="text/javascript">
	 			function verifyMe(id,duration,start,end,service){
	 					$("#vid").val(id);
	 					$("#vduration").val(duration);
	 					$("#vstart").val(start);
	 					$("#vend").val(end);
	 					$("#vdisplay").val(end);
	 					$("#vdate")
	 					$("#vservice").val(duration+"mins -"+service);
	 			}

	 			function deny(id)
	 			{
	 				swal({
			          title: 'Confirm',
			          text: "Are you sure you want to deny this booking?",
			          type: 'warning',
			          showCancelButton: true,
			          confirmButtonColor: '#3085d6',
			          cancelButtonColor: '#d33',
			          confirmButtonText: "Deny",
			        }).then((result) => {
						if(result){
							var form_data = {
								_token: $("input[name=_token]").val(),
								id:id
							};
							$.ajax({
						         url : "{{url('/')}}"+"/admin/deny",
						         data :  form_data,
						         type : "POST",
						        success : function(msg){
						            //success();
						            //console.log(msg);
						           
						           
						            if(msg=="Success"){
						            	success("Booking denied successfully.");
						            	setTimeout(function(){window.location.reload();},1500);
						            }else{
						            	text = msg.split("|")
						           	     error("The system encountered an error. Please contact the administrator." + text[0]);
						           
						            }

						        }
						       }); 
						}
						
			        })
	 			}

	 			function placeValue(id,fname,mname,lname,age,gender,salary)
	 			{

	 				$('#eid').val(id);
	 				$('#efname').val(fname);
	 				$('#emname').val(mname);
	 				$('#elname').val(lname);
	 				$('#eage').val(age);
	 				$('#egender').val(gender);
	 				$('#esalary').val(salary);

	 			}
    //document.getElementById("beg_date").onchange = function() {myFunction()};
			    function add_Personnel(){
			       var form_data={
			       		_token: $("input[name=_token]").val(),
			       		fname: $('#fname').val(),
			       		mname: $('#mname').val(),
			            lname: $('#lname').val(),
			            age: $('#age').val(),
			            gender: $('#gender').val(),
			            salary: $('#salary').val(),
			            ajax: 1
			       };
			       
			       if($('#gender').val()){
						       $.ajax({
						         url : "{{route('personnel.store')}}",
						         data :  form_data,
						         type : "POST",
						        success : function(msg){
						            //success();
						            //console.log(msg);
						            var res = msg.split('|');
						            if(res[0]=="Error"){
						                error("The system encountered an error. Please contact the administrator.");
						            }
						            if(res[0]=="Success"){
						            	success('Personnel added successfully.')
						            	setTimeout(function(){window.location.reload();},1500);
						            }

						        }
						       });
					}else{
						error('Please select a gender.');
					}

			           return false;
			       }

			       function edit_Personnel(){
			       var form_data={
			       		_token: $("input[name=_token]").val(),
			       		id: $('#eid').val(),
			       		fname: $('#efname').val(),
			       		mname: $('#emname').val(),
			            lname: $('#elname').val(),
			            age: $('#eage').val(),
			            gender: $('#egender').val(),
			            salary: $('#esalary').val(),
			            ajax: 1
			       };
			        
			       $.ajax({
			        url : "{{url('/')}}"+"/admin/updatePersonnel",
			         data :  form_data,
			         type : "POST",
			        success : function(msg){
			            //success();
			            console.log(msg);
			            if(msg=="Error"){
			                error("The system encountered an error. Please contact the administrator.");
			            }
			            if(msg=="Success"){
			            	success('Personnel updated.')
			            	setTimeout(function(){window.location.reload();},1500);
			            }

			        }
			       }); 
			           return false;
			       }

  </script>	


      