dnd/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::group(['prefix'=>'admin','middleware'=>'auth'],function () {
	Route::get('/','HomeController@index');
	Route::get('getDeck','HomeController@getDeck');

	//personnel
	Route::resource('personnel','PersonnelController');
	Route::any('updatePersonnel','PersonnelController@updatePersonnel');
	Route::any('deact','PersonnelController@deact');
	Route::any('profile/{id}','PersonnelController@show_prof');
	Route::any('updateUser','UserController@updateUser');
		
	//Personnel schedule
	Route::resource('Psched','PscheduleController');
	Route::any('pSchedMany','PscheduleController@pSchedMany');

	//customer schedule + booking
	Route::resource('Csched','ScheduleController');
	Route::any('booking','ScheduleController@booking');
	Route::any('verifyTime','ScheduleController@verifyTime');
	Route::any('deny','ScheduleController@deny');
	
	//admin only links
	Route::middleware('Checkrole')->group(function () {
		

		//shift
		Route::resource('shift','ShiftController');
		Route::any('updateShift','ShiftController@updateShift');
		Route::any('deact_shift','ShiftController@deact');
			
		//services
		Route::resource('services','ServiceController');
		Route::any('sdeact','ServiceController@sdeact');
		Route::any('updateService','ServiceController@updateService');
		
		//rooms
		Route::resource('rooms','RoomController');
		Route::any('rdeact','RoomController@rdeact');
		Route::any('updateRoom','RoomController@updateRoom');


		//user
		Route::resource('users','UserController',['except'=>['show']]);
		Route::any('backup','UserController@backup');
		
		
		// Route::resource('monkeys', 'MonkeysController', [
		// 	'except' => ['edit', 'create']
		// ]);

		Route::any('deact_user','UserController@deact');
		Route::any('checkUsername', 'UserController@checkUsername');
		Route::any('resetPass', 'UserController@resetPass');
		
		Route::any('databackup','DatabaseBackupController@generateBackup');
	});

	//end admin only links
	
	Route::resource('users', 'UserController', [
			'only' => [ 'show']
	]);

	Route::any('changePass','UserController@changePass');

	Route::get('/rooms/clear/{id}','RoomController@clearRoom');
	Route::any('getTime','ShiftController@getTime');
	Route::any('saveSched','PscheduleController@saveSched');
	Route::any('savebSched','PscheduleController@savebSched');
	Route::any('editshed/{id}','PscheduleController@editshed');
	Route::any('editSched','PscheduleController@editSched');
	//printables
	Route::get('monthlysched/{month}','ReportController@monthlysched');
	Route::get('monthlyCsched/{month}','ReportController@monthlyCsched');

	//notifs
	Route::resource('/notifs', 'NotifController');
	Route::any('/toText', 'NotifController@toText');

	// functions
	Route::any('/getDeck','HomeController@getDeck');
	Route::any('/getRooms','HomeController@getRooms');
	Route::any('/getCschedule','HomeController@getCschedule');

	//test link
	Route::any('/testme','ScheduleController@testme');

	//Assignment
	Route::resource('/assignment','AssignmentController');

	//Deck

	
});


Route::get('/', function () {
      return view('welcome');
    // return redirect()->route('login');
});
// Route::get('/','HomeController@home');
Route::any('/saveCSchedH','HomeController@saveCschedH');
Route::any('/saveCSchedA','HomeController@saveCschedA');

dnd/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="{{asset('img/apple-icon.png')}}">
  <link rel="icon" type="image/png" href="{{asset('img/logo.jpg')}}">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    {{ config('app.name', 'Laravel') }}
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
  <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
  <!-- CSS Files -->
  <link href="{{asset('css/bootstrap.min.css')}}" rel="stylesheet" />
  <link href="{{asset('css/now-ui-dashboard.css?v=1.1.2')}}" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="{{asset('css/pot.css')}}" rel="stylesheet" />
  @yield('extrastyle')
</head>

<body class=" sidebar-mini ">
  <div class="wrapper ">
    @include('layouts/sidebar')
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent  navbar-absolute bg-primary ">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <a class="navbar-brand" href="{{url('/admin')}}"></a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navigation">
            <!-- <form>
              <div class="input-group no-border">
                <input type="text" value="" class="form-control" placeholder="Search...">
                <div class="input-group-append">
                  <div class="input-group-text">
                    <i class="now-ui-icons ui-1_zoom-bold"></i>
                  </div>
                </div>
              </div>
            </form> -->
            <ul class="navbar-nav">
             <!--  <li class="nav-item">
                <a class="nav-link" href="#pablo">
                  <i class="now-ui-icons media-2_sound-wave"></i>
                  <p>
                    <span class="d-lg-none d-md-block">Stats</span>
                  </p>
                </a>
              </li> -->
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="now-ui-icons users_single-02"></i>
                  <p>
                    <span class="d-lg-none d-md-block">Some Actions</span>
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" <span id="nbcount">New Booking</a>
                  <a class="dropdown-item" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Logout</a>
                  <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
     
            @yield('content')

      <!-- Start Footer -->
      <footer class="footer">
        <div class="container-fluid">
          <!-- <nav>
            <ul>
              <li>
                <a href="https://www.creative-tim.com">
                  Creative Tim
                </a>
              </li>
              <li>
                <a href="http://presentation.creative-tim.com">
                  About Us
                </a>
              </li>
              <li>
                <a href="http://blog.creative-tim.com">
                  Blog
                </a>
              </li>
            </ul>
          </nav> -->
          <div class="copyright" id="copyright">
            &copy;
            <script>
              document.getElementById('copyright').appendChild(document.createTextNode(new Date().getFullYear()))
            </script>, Designed by
            <a href="https://www.invisionapp.com" target="_blank">Invision</a>. Coded by
            <a href="https://www.creative-tim.com" target="_blank">Creative Tim</a>.
          </div>
        </div>
      </footer>
    </div>
  </div>
  <!--   Core JS Files   -->
  <script src="{{asset('js/core/jquery.min.js')}}"></script>
  <script src="{{asset('js/core/popper.min.js')}}"></script>
  <script src="{{asset('js/core/bootstrap.min.js')}}"></script>
  <script src="{{asset('js/plugins/perfect-scrollbar.jquery.min.js')}}"></script>
  <script src="{{asset('js/plugins/moment.min.js')}}"></script>
  <!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
  <script src="{{asset('js/plugins/bootstrap-switch.js')}}"></script>
  <!--  Plugin for Sweet Alert -->
  <script src="{{asset('js/plugins/sweetalert2.min.js')}}"></script>
  <!-- Forms Validations Plugin -->
  <script src="{{asset('js/plugins/jquery.validate.min.js')}}"></script>
  <!--  Plugin for the Wizard, full documentation here: https://github.com/VinceG/twitter-bootstrap-wizard -->
  <script src="{{asset('js/plugins/jquery.bootstrap-wizard.js')}}"></script>
  <!--  Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
  <script src="{{asset('js/plugins/bootstrap-selectpicker.js')}}"></script>
  <!--  Plugin for the DateTimePicker, full documentation here: https://eonasdan.github.io/bootstrap-datetimepicker/ -->
  <script src="{{asset('js/plugins/bootstrap-datetimepicker.js')}}"></script>
  <!--  DataTables.net Plugin, full documentation here: https://datatables.net/    -->
  <script src="{{asset('js/plugins/jquery.dataTables.min.js')}}"></script>
  <!--  Plugin for Tags, full documentation here: https://github.com/bootstrap-tagsinput/bootstrap-tagsinputs  -->
  <script src="{{asset('js/plugins/bootstrap-tagsinput.js')}}"></script>
  <!-- Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
  <script src="{{asset('js/plugins/jasny-bootstrap.min.js')}}"></script>
  <!--  Full Calendar Plugin, full documentation here: https://github.com/fullcalendar/fullcalendar    -->
  <script src="{{asset('js/plugins/fullcalendar.min.js')}}"></script>
  <!-- Vector Map plugin, full documentation here: http://jvectormap.com/documentation/ -->
  <script src="{{asset('js/plugins/jquery-jvectormap.js')}}"></script>
  <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
  <script src="{{asset('js/plugins/nouislider.min.js')}}"></script>
  <!--  Google Maps Plugin    -->
  <!-- <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE')}}"></script> -->
  <!-- Chart JS -->
  <script src="{{asset('js/plugins/chartjs.min.js')}}"></script>
  <!--  Notifications Plugin    -->
  <script src="{{asset('js/plugins/bootstrap-notify.js')}}"></script>
  <!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{{asset('js/now-ui-dashboard.min.js?v=1.1.2" type="text/javascript')}}"></script>
  <!-- Now Ui Dashboard DEMO methods, don't include it in your project! -->
  <script src="{{asset('js/swals.js')}}"></script>
  <script src="{{asset('js/func.js')}}"></script>

  @yield('extrajs');
  
</body>

</html>

dnd/resources/views/layouts/sidebar.blade.php
    <div class="sidebar" data-color="red">
      <!--
        Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red | yellow"
    -->
      <div class="logo">
        <a href="{{url('/admin')}}" class="simple-text logo-mini">
          CT
        </a>
        <a href="{{url('/admin')}}" class="simple-text logo-normal">
          CHEETAWAN
        </a>
        <div class="navbar-minimize">
          <button id="minimizeSidebar" class="btn btn-simple btn-icon btn-neutral btn-round">
            <i class="now-ui-icons text_align-center visible-on-sidebar-regular"></i>
            <i class="now-ui-icons design_bullet-list-67 visible-on-sidebar-mini"></i>
          </button>
        </div>
      </div>
      <div class="sidebar-wrapper">
        <div class="user">
          <div class="photo">
            <img src="{{asset('img/mike.png')}}" />
          </div>
          <div class="info">
            <a data-toggle="collapse" href="#collapseExample" class="collapsed">
              <span>
                {{Auth::user()->name}}
                <b class="caret"></b>
              </span>
            </a>
            <div class="clearfix"></div>
            <div class="collapse" id="collapseExample">
              <ul class="nav">
                <li>
                  <a href="{{route('users.show',Auth::user()->id)}}">
                    <span class="sidebar-mini-icon">MP</span>
                    <span class="sidebar-normal">My Profile</span>
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <ul class="nav">
          <li class="{{$curpage=='Dashboard'? 'active' : ''}}">
            <a href="{{url('/admin')}}">
              <i class="now-ui-icons design_app"></i>
              <p>Dashboard</p>
            </a>
          </li>
          <li class="{{$curpage=='Personnel'? 'active' : ''}}">
            <a href="{{url('/admin/personnel')}}">
              <i class="now-ui-icons users_single-02"></i>
              <p>Personnel</p>
            </a>
          </li>
          <li class="{{$curpage=='Schedules'? 'active' : ''}}">
            <a href="#Schedules" data-toggle="collapse">
              <i class="now-ui-icons ui-1_calendar-60"></i>
              <p>
                Schedules
                <b class="caret"></b>
              </p>
            </a>
            <div class="{{$curpage=='Psched' || $curpage=='Csched' || $curpage=='Booking'? '' : 'collapse'}}" id="Schedules">
                      <ul class="nav">
                          <li class="{{$curpage=='Psched'? 'active' : ''}}">
                            <a href="{{url('/admin/Psched')}}">
                              <span class="sidebar-mini-icon">Ps</span>
                              <span class="sidebar-normal"> Personnel Schedule </span>
                            </a>
                          </li>
                          <li class="{{$curpage=='Csched'? 'active' : ''}}">
                            <a href="{{url('/admin/Csched')}}">
                              <span class="sidebar-mini-icon">Cs</span>
                              <span class="sidebar-normal"> Customer Schedule </span>
                            </a>
                          </li>
                          
                      </ul>
              </div>
          </li>
          <li {{ Auth::user()->role_id >1? 'hidden':'' }} class="{{$curpage=='Setting'? 'active' : ''}}">
            <a href="#Settings" data-toggle="collapse">
              <i class="now-ui-icons ui-1_settings-gear-63"></i>
              <p>
                Settings
                <b class="caret"></b>
              </p>
            </a>
            <div class="{{$curpage=='Shift' || $curpage=='Services' || $curpage=='Rooms'? '' : 'collapse'}}" id="Settings">
                      <ul class="nav">
                          <li class="{{$curpage=='Shift'? 'active' : ''}}">
                            <a href="{{url('/admin/shift')}}">
                              <span class="sidebar-mini-icon">Sh</span>
                              <span class="sidebar-normal"> Shift </span>
                            </a>
                          </li>
                          <li class="{{$curpage=='Services'? 'active' : ''}}">
                            <a href="{{url('/admin/services')}}">
                              <span class="sidebar-mini-icon">SC</span>
                              <span class="sidebar-normal"> Services </span>
                            </a>
                          </li>
                          <li class="{{$curpage=='Rooms'? 'active' : ''}}">
                            <a href="{{url('/admin/rooms')}}">
                              <span class="sidebar-mini-icon">RM</span>
                              <span class="sidebar-normal"> Rooms </span>
                            </a>
                          </li>
                          <li class="{{$curpage=='Backup'? 'active' : ''}}">
                            <a href="{{url('/admin/databackup')}}">
                              <span class="sidebar-mini-icon">Db</span>
                              <span class="sidebar-normal"> Backup </span>
                            </a>
                          </li>
                      </ul>
              </div>
          </li>
          <li {{ Auth::user()->role_id >1? 'hidden':'' }} class="{{$curpage=='User'? 'active' : ''}}">
            <a href="{{url('/admin/users')}}">
              <i class="now-ui-icons users_circle-08"></i>
              <p>Users</p>
            </a>
          </li>
        </ul>
      </div>
    </div>
    <script>
       var source = new EventSource('{{url('/admin/toText')}}');
       source.addEventListener('totext', function(event) {
           var dt  = JSON.parse(event.data);
              console.log(dt.forText.length);
              if(dt.forText.length > 0)
              {
                  var audio = new Audio('{{asset("sounds/notif.mp3")}}');
                  audio.play();  
                  func.showNotification('bottom','right',"<b>Alert</b><br>There are currently ("+dt.forText.length+") customer scheduled an hour later. Please send them an SMS confirmation.");
              }
      }, false); 
    </script>